## №1.
Вычислите, по возможности не используя программирование: (5E)-1 где Е – единичная матрица размера 5х5.

In [1]:
import numpy as np

$$ 5E =
\begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0\\
0 & 0 & 1 & 0 & 0\\
0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 1
\end{pmatrix}
$$

$$(5E)^{-1} = 1/5
\begin{pmatrix}
1 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0\\
0 & 0 & 1 & 0 & 0\\
0 & 0 & 0 & 1 & 0\\
0 & 0 & 0 & 0 & 1
\end{pmatrix}
$$

In [2]:
A = 5 * np.identity(5)
print(A)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [3]:
P = np.linalg.pinv(A)
print(P)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


## №2.
Вычислите определитель

\begin{equation}
\left(
\begin{array}{cccc}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9\end{array}
\right)
\end{equation}

In [4]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
print(a)
np.linalg.det(a)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


59.999999999999986

In [5]:
1 * (0 * 9 - 6 * 8) - 2 * (4 * 9 - 6 * 7) + 3 * (4 * 8 - 0)

60

## №3. 
Вычислите матрицу, обратную данной

$\left(
\begin{array}{cccc}
1 & 2 & 3\\
4 & 0 & 6\\
7 & 8 & 9\end{array}
\right)
$

In [6]:
np.linalg.inv(a)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [7]:
np.linalg.matrix_rank(a, 0.0001)

3

Приведите пример матрицы 4х4, ранг которой равен 1.

In [8]:
c = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]], float)
print(c)
np.linalg.matrix_rank(c, 0.0001)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


1

## №4.
Вычислите скалярное произведение двух векторов (1, 5)  и  (2, 8):

In [9]:
f = np.array([1, 5])
d = np.array([2, 8])
np.dot(f, d)

42

## №5.
Вычислите смешанное произведение трех векторов: $(1, 5, 0)$, $(2, 8, 7)$ и $(7, 1.5, 3)$

In [10]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
v = np.cross(a, b)
print(np.inner(v, c))
w = np.cross(b, c)
print(np.inner(w, a))

228.5
228.5
